@echo off
echo Descargando el instalador de Python...
curl https://www.python.org/ftp/python/3.10.0/python-3.10.0-amd64.exe -o python-installer.exe
echo Instalando Python...
python-installer.exe /quiet InstallAllUsers=1 PrependPath=1
@echo off
echo Descargando la biblioteca Librosa...
python -m pip install librosa